name: Auto Blog Deploy

on:
  schedule:
    - cron: '0 6 * * *' # every day at 6AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install
      - run: node scripts/run.js
      - name: Commit changes
        run: |
          git config --global user.name 'bot'
          git config --global user.email 'bot@example.com'
          git add .
          git commit -m "🤖 Auto-update blog posts"
          git push
